name: dino_run
description: A 2D infinite side scroller.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flame: 1.30.0
  flame_audio: 2.11.7
  hive: 2.2.3
  path_provider: 2.1.5
  provider: 6.1.5
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  supabase_flutter: ^2.5.3
  flutter_dotenv: ^6.0.0

dev_dependencies:
  hive_generator: 2.0.1
  build_runner: 2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/cinematics/
    - assets/images/parallax/
    - assets/images/AngryPig/
    - assets/images/Bat/
    - assets/images/Rino/
    - assets/images/Desert/
    - assets/images/MontaÃ±as/
    - assets/audio/
    - .env

  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide/Audiowide-Regular.ttf
